"""Building definitions. All values data-driven."""
BUILDINGS = {
    "drill_rig": {
        "id": "drill_rig",
        "name": "Drill Rig",
        "description": "Passive ore production.",
        "category": "extraction",
        "unlock_tech": "passive_drilling",
        "cost": {"ore": 15},
        "effects": {"ore_per_second": 0.35},
        "oxygen_upkeep": 0.01,
        "max_per_run": 6,
    },
    "hand_drill_bay": {
        "id": "hand_drill_bay",
        "name": "Hand Drill Upgrade Bay",
        "description": "Improves active tap yield.",
        "category": "extraction",
        "unlock_tech": "efficient_strikes_i",
        "cost": {"ore": 20},
        "effects": {"ore_per_tap": 1.0},
        "oxygen_upkeep": 0.0,
        "max_per_run": 2,
    },
    "solar_array": {
        "id": "solar_array",
        "name": "Solar Array",
        "description": "Passive power production.",
        "category": "sustainment",
        "unlock_tech": "power_routing",
        "cost": {"ore": 25},
        "effects": {"power_per_second": 0.50},
        "oxygen_upkeep": 0.0,
        "max_per_run": 4,
    },
    "oxygen_recycler": {
        "id": "oxygen_recycler",
        "name": "Oxygen Recycler",
        "description": "Reduces oxygen drain.",
        "category": "sustainment",
        "unlock_tech": "improved_recycling",
        "cost": {"ore": 30, "power": 2},
        "effects": {"oxygen_drain_flat": -0.03},
        "oxygen_upkeep": 0.0,
        "max_per_run": 3,
    },
    "refinery": {
        "id": "refinery",
        "name": "Refinery",
        "description": "Converts ore into alloy.",
        "category": "industrial",
        "unlock_tech": "smelting_protocols",
        "cost": {"ore": 45, "power": 4},
        "effects": {"ore_consumption": 0.6, "alloy_per_second": 0.10},
        "oxygen_upkeep": 0.015,
        "max_per_run": 3,
    },
    "survey_scanner": {
        "id": "survey_scanner",
        "name": "Survey Scanner",
        "description": "Reveals 2 sockets and 1 hidden node.",
        "category": "expansion",
        "unlock_tech": "deep_survey",
        "cost": {"ore": 35, "power": 3},
        "effects": {"unlock_sockets": 2, "reveal_crystal_nodes": 1},
        "oxygen_upkeep": 0.005,
        "max_per_run": 1,
    },
    "crystal_harvester": {
        "id": "crystal_harvester",
        "name": "Crystal Harvester",
        "description": "Extracts rare crystal.",
        "category": "advanced",
        "unlock_tech": "guidance_systems",
        "cost": {"ore": 50, "power": 6, "alloy": 10},
        "effects": {"crystal_per_second": 0.05},
        "oxygen_upkeep": 0.02,
        "max_per_run": 2,
    },
    "launch_assembly_bay": {
        "id": "launch_assembly_bay",
        "name": "Launch Assembly Bay",
        "description": "Enables rocket part construction.",
        "category": "escape",
        "unlock_tech": "launch_assembly",
        "cost": {"ore": 60, "power": 8, "alloy": 12},
        "effects": {"enable_rocket_assembly": True},
        "oxygen_upkeep": 0.02,
        "max_per_run": 1,
    },
}
