"""Tech tree definitions. 12 techs across 3 branches."""
TECHS = {
    "efficient_strikes_i": {
        "id": "efficient_strikes_i",
        "name": "Efficient Strikes I",
        "branch": "extraction",
        "description": "Ore per tap x1.25",
        "cost": {"ore": 12},
        "prerequisites": [],
        "effects": {"ore_per_tap_multiplier": 1.25},
    },
    "passive_drilling": {
        "id": "passive_drilling",
        "name": "Passive Drilling",
        "branch": "extraction",
        "description": "Unlocks Drill Rig",
        "cost": {"ore": 20},
        "prerequisites": ["efficient_strikes_i"],
        "effects": {"unlock_building_ids": ["drill_rig"]},
    },
    "deep_survey": {
        "id": "deep_survey",
        "name": "Deep Survey",
        "branch": "extraction",
        "description": "Unlocks Survey Scanner",
        "cost": {"ore": 35, "power": 2},
        "prerequisites": ["passive_drilling"],
        "effects": {"unlock_building_ids": ["survey_scanner"]},
    },
    "precision_extraction": {
        "id": "precision_extraction",
        "name": "Precision Extraction",
        "branch": "extraction",
        "description": "Ore/sec x1.15",
        "cost": {"ore": 45, "power": 4},
        "prerequisites": ["deep_survey"],
        "effects": {"ore_per_second_multiplier": 1.15},
    },
    "air_filters": {
        "id": "air_filters",
        "name": "Air Filters",
        "branch": "sustainment",
        "description": "Oxygen drain x0.92",
        "cost": {"ore": 16},
        "prerequisites": [],
        "effects": {"oxygen_drain_multiplier": 0.92},
    },
    "improved_recycling": {
        "id": "improved_recycling",
        "name": "Improved Recycling",
        "branch": "sustainment",
        "description": "Unlocks Oxygen Recycler",
        "cost": {"ore": 28, "power": 2},
        "prerequisites": ["air_filters"],
        "effects": {"unlock_building_ids": ["oxygen_recycler"]},
    },
    "power_routing": {
        "id": "power_routing",
        "name": "Power Routing",
        "branch": "sustainment",
        "description": "Power/sec x1.20 + Solar Array",
        "cost": {"ore": 36},
        "prerequisites": ["air_filters"],
        "effects": {"power_per_second_multiplier": 1.20, "unlock_building_ids": ["solar_array"]},
    },
    "pressure_seals": {
        "id": "pressure_seals",
        "name": "Pressure Seals",
        "branch": "sustainment",
        "description": "Oxygen drain x0.90",
        "cost": {"ore": 50, "power": 4, "alloy": 4},
        "prerequisites": ["improved_recycling", "power_routing"],
        "effects": {"oxygen_drain_multiplier": 0.90},
    },
    "smelting_protocols": {
        "id": "smelting_protocols",
        "name": "Smelting Protocols",
        "branch": "escape",
        "description": "Unlocks Refinery",
        "cost": {"ore": 26, "power": 2},
        "prerequisites": ["passive_drilling"],
        "effects": {"unlock_building_ids": ["refinery"]},
    },
    "launch_assembly": {
        "id": "launch_assembly",
        "name": "Launch Assembly",
        "branch": "escape",
        "description": "Unlocks Launch Bay + Hull",
        "cost": {"ore": 55, "power": 6, "alloy": 6},
        "prerequisites": ["smelting_protocols"],
        "effects": {"unlock_building_ids": ["launch_assembly_bay"], "rocket_part_unlocks": ["hull"]},
    },
    "guidance_systems": {
        "id": "guidance_systems",
        "name": "Guidance Systems",
        "branch": "escape",
        "description": "Unlocks Guidance + Crystal Harvester",
        "cost": {"ore": 65, "power": 8, "alloy": 8, "crystal": 2},
        "prerequisites": ["launch_assembly"],
        "effects": {"unlock_building_ids": ["crystal_harvester"], "rocket_part_unlocks": ["guidance"]},
    },
    "life_support_integration": {
        "id": "life_support_integration",
        "name": "Life Support Integration",
        "branch": "escape",
        "description": "Unlocks Life Support + Engine",
        "cost": {"ore": 70, "power": 8, "alloy": 10, "crystal": 3},
        "prerequisites": ["launch_assembly"],
        "effects": {"rocket_part_unlocks": ["engine", "life_support"]},
    },
}
